-- Hippo store — catalog + store_content_blocks (deterministic UUIDs)
-- Apply after tenant schema + tables exist (pnpm schema:provision or Studio).
--
-- Automated (recommended): from this app directory, same .env.local as the storefront:
--   pnpm seed:apply
-- The API resolves your tenant from AURORA_API_KEY and substitutes __TENANT_UUID__ / __TENANT_SCHEMA__.
--
-- Manual: 1) Replace __TENANT_UUID__ and __TENANT_SCHEMA__ (see emit-seed-sql.mjs header example).
--         2) psql $DATABASE_URL -v ON_ERROR_STOP=1 -f init/seed.sql
--         or paste into Studio SQL editor.
--
-- Re-run safe: deletes seed SKUs/slugs for this vertical before insert.
-- After apply: reindex Meilisearch for the tenant.

BEGIN;

-- Clean previous seed rows for this vertical (idempotent)
DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug LIKE 'seed-cb-store-%';
DELETE FROM __TENANT_SCHEMA__.products WHERE tenant_id = '__TENANT_UUID__'::uuid AND sku LIKE 'SEED-HIPPO-STORE-%';
DELETE FROM __TENANT_SCHEMA__.categories WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug IN ('hippo-store-tools', 'hippo-store-garden', 'hippo-store-paint-decor');
DELETE FROM __TENANT_SCHEMA__.zones WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug = 'hippo-store-seed-zone';
DELETE FROM __TENANT_SCHEMA__.vendors WHERE tenant_id = '__TENANT_UUID__'::uuid AND id = '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid;

INSERT INTO __TENANT_SCHEMA__.vendors (id, tenant_id, name, email, status, created_at, updated_at)
VALUES ('507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, '__TENANT_UUID__'::uuid, 'Seed — Hippo Store supply', 'seed-store@example.com', 'active', now(), now());

INSERT INTO __TENANT_SCHEMA__.zones (id, tenant_id, slug, name, sort_order, vendor_id, created_at, updated_at)
VALUES ('ef226bd0-bc37-4d6e-9ebc-a66d4e42c905'::uuid, '__TENANT_UUID__'::uuid, 'hippo-store-seed-zone', 'DIY floor', 1, '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('ab3bbe21-6945-4959-b1ba-18bb74535cef'::uuid, '__TENANT_UUID__'::uuid, 'Tools', 'hippo-store-tools', 'ef226bd0-bc37-4d6e-9ebc-a66d4e42c905'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('9fd8180e-f6d0-4822-9011-ebd91703c33a'::uuid, '__TENANT_UUID__'::uuid, 'Garden & outdoor', 'hippo-store-garden', 'ef226bd0-bc37-4d6e-9ebc-a66d4e42c905'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('b1f9d0e9-1209-4ecc-b7ea-614f8e99b662'::uuid, '__TENANT_UUID__'::uuid, 'Paint & decor', 'hippo-store-paint-decor', 'ef226bd0-bc37-4d6e-9ebc-a66d4e42c905'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('4141f556-89eb-4503-a026-2cc58e06229c'::uuid, '__TENANT_UUID__'::uuid, 'Cordless drill driver kit (demo)', '18V brushless motor, 2 batteries, charger — for shelves and fixtures.', 129, 'SEED-HIPPO-STORE-01', 50, 'https://images.pexels.com/photos/3877525/pexels-photo-3877525.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'ab3bbe21-6945-4959-b1ba-18bb74535cef'::uuid, '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, 'hero, new_arrival', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('c6cb87a5-26ec-4aef-b2d7-e30a946ab320'::uuid, '__TENANT_UUID__'::uuid, 'Metric socket set', 'Chrome vanadium sockets 8–19mm with ratchet.', 48, 'SEED-HIPPO-STORE-02', 50, 'https://images.pexels.com/photos/4480531/pexels-photo-4480531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'ab3bbe21-6945-4959-b1ba-18bb74535cef'::uuid, '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('263d66cd-4944-4065-8089-743939168d9d'::uuid, '__TENANT_UUID__'::uuid, 'Telescopic hedge trimmer', 'Reach tall hedges safely from the ground.', 89, 'SEED-HIPPO-STORE-03', 50, 'https://images.pexels.com/photos/7813043/pexels-photo-7813043.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '9fd8180e-f6d0-4822-9011-ebd91703c33a'::uuid, '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, 'seasonal', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('7c77900e-2b45-4683-87f6-d13e04f25f53'::uuid, '__TENANT_UUID__'::uuid, 'Compost bin 220L', 'Ventilated garden composter with lid.', 64, 'SEED-HIPPO-STORE-04', 50, 'https://images.pexels.com/photos/5503338/pexels-photo-5503338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '9fd8180e-f6d0-4822-9011-ebd91703c33a'::uuid, '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('25f1f0f1-40b6-4431-b3ae-67d6dc321c1c'::uuid, '__TENANT_UUID__'::uuid, 'Matt emulsion 10L — soft white', 'Washable wall paint for living rooms and bedrooms.', 42, 'SEED-HIPPO-STORE-05', 50, 'https://images.pexels.com/photos/7217981/pexels-photo-7217981.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'b1f9d0e9-1209-4ecc-b7ea-614f8e99b662'::uuid, '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('710b4190-6bba-4766-b02c-fd416a9151fa'::uuid, '__TENANT_UUID__'::uuid, 'Decorator’s roller set', '9" roller, tray, and extension pole.', 24, 'SEED-HIPPO-STORE-06', 50, 'https://images.pexels.com/photos/5691624/pexels-photo-5691624.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'b1f9d0e9-1209-4ecc-b7ea-614f8e99b662'::uuid, '507d4a69-d266-42d3-b03d-ab1dc6921b98'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('d4d3d628-724c-4f7f-b1ae-5a8c4d14bd6c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-products', 0, 'home', 'home_main_feed', 'full', 'product_list', 'Project starters the trade desk promotes', 'Drills, garden lines, and paint — curated SKUs for weekend DIY missions.', NULL, NULL, NULL, NULL, '4141f556-89eb-4503-a026-2cc58e06229c,c6cb87a5-26ec-4aef-b2d7-e30a946ab320,263d66cd-4944-4065-8089-743939168d9d,7c77900e-2b45-4683-87f6-d13e04f25f53,25f1f0f1-40b6-4431-b3ae-67d6dc321c1c,710b4190-6bba-4766-b02c-fd416a9151fa', NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('aeea2547-5b03-4444-8683-faed9b80f086'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-search', 1, 'home', 'home_main_feed', 'full', 'search_terms', 'Aisles shoppers combine', 'OR search pulls tools, consumables, and outdoor lines in one grid.', NULL, NULL, NULL, NULL, NULL, 'drill, roller, hedge, compost, emulsion, socket set', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('46b19b7c-0e39-4b76-8269-f37549f329c6'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-blurb', 2, 'home', 'home_main_feed', 'full', 'blurb', 'Plan the room, then the basket', NULL, 'Holmes bundles by project; CMS blocks sell seasonal paint and garden without redeploying. For You nudges missing fasteners and safety kit.', NULL, '/catalogue', 'Browse departments', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('765716af-7e1e-4935-9fbe-71cdc5efda57'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-half-a', 3, 'home', 'home_main_feed', 'half', 'blurb', 'Power tools & fixings', NULL, 'Cordless kits and socket sets for shelves, curtain rails, and small builds — keep half-width for dense mobile layouts.', NULL, '/catalogue?category=hippo-store-tools', 'Tools', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('1b07d1ad-157b-4076-9edd-1565f9bbc266'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-half-b', 4, 'home', 'home_main_feed', 'half', 'blurb', 'Garden weekend', NULL, 'Trimming, composting, and outdoor storage — pair with paint for fence refresh weekends.', NULL, '/catalogue?category=hippo-store-garden', 'Garden', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('23c34475-d950-47db-beab-5e5ff589effa'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-image', 5, 'home', 'home_main_feed', 'full', 'image_blurb', 'Bank holiday project event', NULL, 'Deals ribbon for multi-buy paint, tool bundles, and outdoor prep.', 'https://images.pexels.com/photos/36378855/pexels-photo-36378855.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('ff007946-114b-43c6-9b7e-8644df75691c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-below-well', 1, 'home', 'home_below_context_well', 'full', 'blurb', 'Click & collect windows', NULL, 'Cut-off times, branch stock, and weather notes for outdoor work.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('ab75d85b-31a0-4c92-b0af-88c9f20e196a'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-between-missions', 1, 'home', 'home_between_missions_and_feed', 'full', 'blurb', 'How-to & projects', NULL, 'Short line linking workshops, measure services, or YouTube-style project IDs — two sentences max.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('4141460f-9eb9-44a1-adb7-05bf033dfea4'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-below-feed', 1, 'home', 'home_below_feed', 'full', 'blurb', 'Need meal ideas after DIY day?', NULL, 'Recipe missions still work for meal kits and grocery cross-sell.', NULL, '/recipes', 'Recipe ideas', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9db1f349-8337-4b0c-978b-bc9be843709e'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-for-you-blocks', 1, 'for_you', 'for_you_below_cart_blocks', 'full', 'search_terms', 'Finish the job', 'Blades, sandpaper, brushes, and PPE before checkout.', NULL, NULL, NULL, NULL, NULL, 'roller, brush, sandpaper, gloves, tape, drill bit', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('c1dad25c-bc3b-45a3-b3e2-1d60c3ad3b70'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-for-you-header', 1, 'for_you', 'for_you_below_header', 'full', 'blurb', 'Basket-aware suggestions', NULL, 'Holmes fills bundles; CMS adds static “don’t forget filler” copy.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9a5a9d59-3b3a-4739-bdff-a0d6e821942d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-above', 1, 'catalogue', 'catalogue_above_grid', 'full', 'blurb', 'Departments in one grid', NULL, 'Filter tools, garden, and paint-decor. Search accepts project phrases (“fence stain Saturday”).', NULL, '/catalogue', 'Reset filters', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b8843b7f-fb3c-4155-8278-4abe7ba3cbca'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-below', 1, 'catalogue', 'catalogue_below_filters', 'full', 'search_terms', 'Trending searches', 'Broad OR across DIY staples.', NULL, NULL, NULL, NULL, NULL, 'drill, paint, roller, garden, compost, socket', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b6bd1cb2-b72c-44c8-99a4-2b617aec4755'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-paint', 2, 'catalogue', 'catalogue_below_filters', 'full', 'blurb', 'Paint & decor aisle', NULL, 'You’re in Paint & decor — upsell rollers, trays, and masking tape. Link to tools for prep work.', NULL, '/catalogue?category=hippo-store-tools', 'Tools', NULL, NULL, NULL, NULL, NULL, 'hippo-store-paint-decor', now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('a740064d-4bab-478d-bb87-54ad22246341'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-pdp-tabs', 1, 'product_detail', 'pdp_below_tabs', 'full', 'blurb', 'Specs & safety', NULL, 'Torque, voltage, VOC, and PPD warnings belong here — keep legal copy out of titles.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('71b8ab2b-32df-40f3-8177-61304fc3b88b'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-pdp-context', 1, 'product_detail', 'pdp_below_context', 'full', 'blurb', 'Returns & guarantees', NULL, 'Link to your store policy for opened paint and tool warranties.', NULL, '/about', 'Our standards', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('d2941805-9e69-4bd1-9b57-a1f1959d09b9'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-title', 1, 'recipe', 'recipe_below_title', 'full', 'blurb', 'Project night fuel', NULL, 'Tie recipe missions to quick meals when customers shop long DIY sessions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('1cd88840-cc30-436b-b711-74d512981d66'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-ingredients', 1, 'recipe', 'recipe_below_ingredients', 'full', 'blurb', 'Missing an ingredient?', NULL, 'Search or For You — Holmes bundles grocery add-ons with the cart.', NULL, '/for-you', 'Open For You', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('044cc12e-6459-40fa-ac27-9dc2f071863c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-index', 1, 'recipe_index', 'recipes_index_below_header', 'full', 'blurb', 'Meals between coats', NULL, 'Short cooks that fit drying times — great for hardware weekend traffic.', NULL, '/', 'Back to home', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('0768555c-260c-4bca-9a6f-87e993247c21'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-checkout-summary', 1, 'checkout', 'checkout_above_summary', 'full', 'blurb', 'Almost done', NULL, 'Heavy or oversized lines may need separate delivery — confirm with ops copy.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('03429937-ccf5-4c30-9b85-727537c27353'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-checkout-sidebar', 1, 'checkout', 'checkout_sidebar', 'full', 'blurb', 'Need help?', NULL, 'Trade desk hours, hire services, and tool hotline — sidebar CMS slot.', NULL, '/about', 'Contact', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('cb8b3294-f8d0-41c3-bbd3-907c39907d96'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cart-above', 1, 'cart', 'cart_above_lines', 'full', 'blurb', 'Review quantities', NULL, 'Bundles sync with For You — drop duplicate heavy items before route planning.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('118cf4f7-16dc-41f3-9d4e-1af38d9351d6'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cart-below-bundle', 1, 'cart', 'cart_below_bundle', 'full', 'blurb', 'Complete the project', NULL, 'Cross-sell consumables: screws, anchors, filler.', NULL, '/catalogue?category=hippo-store-tools', 'Tools', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('acb483f4-f5d2-47b1-aebf-1381a3a9062f'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-offers', 1, 'offers', 'offers_below_header', 'full', 'blurb', 'Live savings', NULL, 'Multi-buy paint, garden bundles, and tool kits — keep the strip short.', NULL, '/catalogue', 'Shop all', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('32fb8df7-fdee-49de-9f2e-1d2d34972c65'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-promotions', 1, 'promotions', 'promotions_below_header', 'full', 'blurb', 'Bank holiday & season', NULL, 'BBQ build, spring garden, winter heating prep — align with local campaigns.', NULL, '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('362abd57-5702-4ace-9401-2f0555baf944'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-about', 1, 'about', 'about_main', 'full', 'image_blurb', 'Hippo Store', NULL, 'Catalogue + Holmes + CMS blocks let merchandisers run DIY events without app releases.', 'https://images.pexels.com/photos/3926796/pexels-photo-3926796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/catalogue', 'Start shopping', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
COMMIT;
