BEGIN;

DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug LIKE 'seed-cb-store-%';
DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND (page, region, title) IN (('home', 'home_main_feed', 'Starter picks with sizes you can trust'), ('home', 'home_main_feed', 'Search by job, not jargon'), ('home', 'home_main_feed', 'Measure once, basket once'), ('home', 'home_main_feed', 'Tools & prep'), ('home', 'home_main_feed', 'Fasteners & structure'), ('home', 'home_main_feed', 'Bank holiday build event'), ('home', 'home_below_context_well', 'Click & collect windows'), ('home', 'home_between_missions_and_feed', 'How-to & projects'), ('home', 'home_below_feed', 'Need meal ideas after DIY day?'), ('for_you', 'for_you_below_cart_blocks', 'Complete the fixings list'), ('for_you', 'for_you_below_header', 'What pros grab last'), ('catalogue', 'catalogue_above_grid', 'Spec-first catalogue'), ('catalogue', 'catalogue_below_filters', 'Trending searches'), ('catalogue', 'catalogue_below_filters', 'In paint & prep'), ('product_detail', 'pdp_below_tabs', 'Specs, loads & safety'), ('product_detail', 'pdp_below_context', 'Returns & trade desk'), ('recipe', 'recipe_below_title', 'Project night fuel'), ('recipe', 'recipe_below_ingredients', 'Missing an ingredient?'), ('recipe_index', 'recipes_index_below_header', 'Meals between coats'), ('checkout', 'checkout_above_summary', 'Delivery & collection'), ('checkout', 'checkout_sidebar', 'Trade desk & hire'), ('cart', 'cart_above_lines', 'Weights & lengths'), ('cart', 'cart_below_bundle', 'Finish strong'), ('offers', 'offers_below_header', 'Trade deals'), ('promotions', 'promotions_below_header', 'Seasonal yard & site'), ('about', 'about_main', 'Your trade-ready hardware story'));

INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9b12c805-a7b5-43bb-86fb-28e5a70195e7'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-products', 0, 'home', 'home_main_feed', 'full', 'product_list', 'Starter picks with sizes you can trust', 'Spec-led screws, timber, paint, and brackets — picked for real projects, not generic aisles.', NULL, NULL, NULL, NULL, 'c65ff313-d80d-4dba-bfae-516c472ffb18,df3af343-0b79-496a-b09f-6961731c35f8,7a341f16-92e6-4028-b7be-a8bc99498433,3a08e5ab-49fc-4bb9-9e66-d732c32477cf,886d8791-3890-4498-8525-8aa36390e28e,509e6597-048b-464d-956f-b56a7b66169e,980d437f-7a27-4f04-9b3c-883287e98b27,dcea4a4f-ed51-40da-8aaf-0cfbd7c565ca,5348ddce-1e8a-4417-a41d-7a7862b74964,d3e66863-fbe2-402d-bb13-fe8fe1cd1bc1,8dcbe06a-15d9-43ce-b03a-ff9d0a01233f,757b851a-fa07-4ca4-87bf-a39f6c1d1caa', NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9e60a906-1da1-43aa-8b3c-2a17b31b0d34'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-search', 1, 'home', 'home_main_feed', 'full', 'search_terms', 'Search by job, not jargon', 'One OR search spans tools, fasteners, timber, paint, and sealants — how trades actually shop.', NULL, NULL, NULL, NULL, NULL, 'M8 bolt, PVA glue, CLS stud, emulsion, shelf bracket, masonry bit', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('3cb6e54d-2331-47a2-b956-227d878000f0'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-blurb', 2, 'home', 'home_main_feed', 'full', 'blurb', 'Measure once, basket once', NULL, 'SKUs carry grades, sizes, and coverage so customers self-serve. Use CMS strips for branch hours and click‑and‑collect; let For You suggest the tape, plugs, and PPE they forgot.', NULL, '/catalogue', 'Browse all departments', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('413c8d2e-b1a1-4921-90c7-914ea0622ac0'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-half-a', 3, 'home', 'home_main_feed', 'half', 'blurb', 'Tools & prep', NULL, 'Drills, levels, and bits with torque and accuracy called out — pair with fasteners from the next tile so nothing is under-spec.', NULL, '/catalogue?category=template-store-tools', 'Tools & measuring', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6f274ec3-8eb3-404d-84a3-ec7dc829f550'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-half-b', 4, 'home', 'home_main_feed', 'half', 'blurb', 'Fasteners & structure', NULL, 'Screws, bolts, hangers, and brackets with load hints — the layer shoppers add after timber and before paint.', NULL, '/catalogue?category=template-store-fasteners', 'Screws & bolts', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6b352a3e-7b38-4bcc-b474-274ab6d229cd'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-image', 5, 'home', 'home_main_feed', 'full', 'image_blurb', 'Bank holiday build event', NULL, 'Hero slot for multi-buy paint, timber packs, and outdoor prep — keep the CTA to offers or a trade weekend.', 'https://images.pexels.com/photos/12340557/pexels-photo-12340557.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9ba64ebc-8bc7-48b1-9e00-11bcca2b0a5b'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-below-well', 1, 'home', 'home_below_context_well', 'full', 'blurb', 'Click & collect windows', NULL, 'Cut-off times, branch stock, and weather notes for outdoor work.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('672413e5-409f-434c-8feb-57435de92e05'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-between-missions', 1, 'home', 'home_between_missions_and_feed', 'full', 'blurb', 'How-to & projects', NULL, 'Short line linking workshops, measure services, or YouTube-style project IDs — two sentences max.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('5eda4ae1-dc8e-4bc0-8bb0-aa960506024d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-below-feed', 1, 'home', 'home_below_feed', 'full', 'blurb', 'Need meal ideas after DIY day?', NULL, 'Recipe missions still work for meal kits and grocery cross-sell.', NULL, '/recipes', 'Recipe ideas', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('aeaef8c8-fdf3-493a-89e5-ff6eedb0c0de'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-for-you-blocks', 1, 'for_you', 'for_you_below_cart_blocks', 'full', 'search_terms', 'Complete the fixings list', 'OR search for sealant, plugs, and abrasives shoppers tack on after the big tools.', NULL, NULL, NULL, NULL, NULL, 'wall plug, masking tape, sandpaper, gloves, silicone, wood glue', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('a53ee242-70db-4932-a67a-50721b6cc13c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-for-you-header', 1, 'for_you', 'for_you_below_header', 'full', 'blurb', 'What pros grab last', NULL, 'Holmes fills bundles; CMS reminds about VOC windows, PPE, and spare fixings before checkout.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('8ecad4dd-6600-4ba9-b790-ada70328830d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-above', 1, 'catalogue', 'catalogue_above_grid', 'full', 'blurb', 'Spec-first catalogue', NULL, 'Jump between tools, timber, adhesives, and brackets. Search likes project shorthand (“18mm ply”, “M8 bolt”, “shelf bracket”).', NULL, '/catalogue', 'Reset filters', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9f939cb2-dcd7-4f6e-a548-ec27a7f84d57'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-below', 1, 'catalogue', 'catalogue_below_filters', 'full', 'search_terms', 'Trending searches', 'Broad OR across trade staples and consumables.', NULL, NULL, NULL, NULL, NULL, 'timber, bracket, PVA, emulsion, coach screw, spirit level', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('1aa70a40-5ffa-4281-8a23-caec5a207bed'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-paint', 2, 'catalogue', 'catalogue_below_filters', 'full', 'blurb', 'In paint & prep', NULL, 'Surface prep wins jobs — nudge primer, tape, and roller kits, then deep-link to fasteners for skirting and shelves.', NULL, '/catalogue?category=template-store-fasteners', 'Screws & fixings', NULL, NULL, NULL, NULL, NULL, 'template-store-paint-decor', now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('bafa32c3-50d5-42fc-8739-5ea4e10dff02'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-pdp-tabs', 1, 'product_detail', 'pdp_below_tabs', 'full', 'blurb', 'Specs, loads & safety', NULL, 'Put torque, voltage, VOC, coverage m²/L, and structural disclaimers here — titles stay scannable.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('5398c872-c011-4e1d-9072-f6a169f34fc9'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-pdp-context', 1, 'product_detail', 'pdp_below_context', 'full', 'blurb', 'Returns & trade desk', NULL, 'Paint tint returns, blade warranties, and damaged-sheet claims — point to trade desk hours.', NULL, '/about', 'Our standards', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('bf79042a-b30c-4d1e-b5d2-31b80ac29db2'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-title', 1, 'recipe', 'recipe_below_title', 'full', 'blurb', 'Project night fuel', NULL, 'Tie recipe missions to quick meals when customers shop long DIY sessions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('3e06f3b6-d0ba-429c-ac33-ad8ea5b7cb7d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-ingredients', 1, 'recipe', 'recipe_below_ingredients', 'full', 'blurb', 'Missing an ingredient?', NULL, 'Search or For You — Holmes bundles grocery add-ons with the cart.', NULL, '/for-you', 'Open For You', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('95ef04d1-ab6c-478a-b40c-7c10458dcfb1'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-index', 1, 'recipe_index', 'recipes_index_below_header', 'full', 'blurb', 'Meals between coats', NULL, 'Short cooks that fit drying times — great for hardware weekend traffic.', NULL, '/', 'Back to home', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6feb6bae-542b-4611-970e-66bee5e4a782'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-checkout-summary', 1, 'checkout', 'checkout_above_summary', 'full', 'blurb', 'Delivery & collection', NULL, 'Timber and sheet goods may need vehicle collection — call out cut-off times for same-day pickup.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('ecc6d16a-a207-4a52-9540-d12a6e220a83'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-checkout-sidebar', 1, 'checkout', 'checkout_sidebar', 'full', 'blurb', 'Trade desk & hire', NULL, 'Cut lists, van hire, and broken-tool swaps — short line to the humans behind the catalogue.', NULL, '/about', 'Contact', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('decdb071-1dfd-4718-a63e-4cbd1946aaa0'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cart-above', 1, 'cart', 'cart_above_lines', 'full', 'blurb', 'Weights & lengths', NULL, 'Double-check sheet sizes and bag counts — oversize timber can blow delivery slots.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e3eed74a-1aff-4130-ac71-55fbec491feb'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cart-below-bundle', 1, 'cart', 'cart_below_bundle', 'full', 'blurb', 'Finish strong', NULL, 'Nudge adhesives, brackets, and masking consumables once the big tools are in.', NULL, '/catalogue?category=template-store-adhesives', 'Adhesives', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('1d8f0c8f-39c3-4831-8d07-4c101aae6692'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-offers', 1, 'offers', 'offers_below_header', 'full', 'blurb', 'Trade deals', NULL, 'Multi-buy paint, timber packs, and fastener trays — mirror what your trade counter shouts.', NULL, '/catalogue', 'Shop all', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('270af101-7ec1-4278-84b7-c31054ddc3de'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-promotions', 1, 'promotions', 'promotions_below_header', 'full', 'blurb', 'Seasonal yard & site', NULL, 'Wet-season sealants, frost prep, and bank-holiday timber — sync with local weather and events.', NULL, '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('679c6ac5-f6f6-4021-bdaa-02fb8f09cfe3'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-about', 1, 'about', 'about_main', 'full', 'image_blurb', 'Your trade-ready hardware story', NULL, 'Spec-rich SKUs, structured departments, and CMS rails that sound like your trade counter — no bespoke app required.', 'https://images.pexels.com/photos/4888895/pexels-photo-4888895.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/catalogue', 'Start shopping', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
COMMIT;
