-- Aurora template (store) — catalog + store_content_blocks (deterministic UUIDs)
-- Apply after tenant schema + tables exist (pnpm schema:provision or Studio).
--
-- 1) Replace __TENANT_UUID__ with your Aurora tenant id (UUID with dashes).
-- 2) Replace __TENANT_SCHEMA__ with tenant_<uuid with underscores not dashes>
--    Example: uuid 550e8400-e29b-41d4-a716-446655440000 -> schema tenant_550e8400_e29b_41d4_a716_446655440000
--
-- 3) Run: psql $DATABASE_URL -v ON_ERROR_STOP=1 -f init/seed.sql
--    or paste into Studio SQL editor (adjust search_path if needed).
--
-- Re-run safe: deletes seed SKUs/slugs for this vertical before insert.
-- After apply: reindex Meilisearch for the tenant.

BEGIN;

-- Clean previous seed rows for this vertical (idempotent)
DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug LIKE 'seed-cb-store-%';
DELETE FROM __TENANT_SCHEMA__.products WHERE tenant_id = '__TENANT_UUID__'::uuid AND sku LIKE 'SEED-TEMPLATE-STORE-%';
DELETE FROM __TENANT_SCHEMA__.categories WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug IN ('template-store-tools', 'template-store-garden', 'template-store-paint-decor');
DELETE FROM __TENANT_SCHEMA__.zones WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug = 'template-store-seed-zone';
DELETE FROM __TENANT_SCHEMA__.vendors WHERE tenant_id = '__TENANT_UUID__'::uuid AND id = 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid;

INSERT INTO __TENANT_SCHEMA__.vendors (id, tenant_id, name, email, status, created_at, updated_at)
VALUES ('f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, '__TENANT_UUID__'::uuid, 'Seed — Example Store supply', 'seed-store@example.com', 'active', now(), now());

INSERT INTO __TENANT_SCHEMA__.zones (id, tenant_id, slug, name, sort_order, vendor_id, created_at, updated_at)
VALUES ('a872f273-07b2-430b-9bfe-9d4ce3c06d9e'::uuid, '__TENANT_UUID__'::uuid, 'template-store-seed-zone', 'DIY floor', 1, 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('fe86dce1-c9f6-4f53-a08e-bf7c11eaf888'::uuid, '__TENANT_UUID__'::uuid, 'Tools', 'template-store-tools', 'a872f273-07b2-430b-9bfe-9d4ce3c06d9e'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('c0e11c0d-65dc-4682-88a2-7eb464fe917b'::uuid, '__TENANT_UUID__'::uuid, 'Garden & outdoor', 'template-store-garden', 'a872f273-07b2-430b-9bfe-9d4ce3c06d9e'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('673df80c-a68f-44fe-a7e6-ee14432b92b6'::uuid, '__TENANT_UUID__'::uuid, 'Paint & decor', 'template-store-paint-decor', 'a872f273-07b2-430b-9bfe-9d4ce3c06d9e'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, brand, price, sku, ean, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('c65ff313-d80d-4dba-bfae-516c472ffb18'::uuid, '__TENANT_UUID__'::uuid, 'Cordless drill driver kit (demo)', '18V brushless motor, 2 batteries, charger — for shelves and fixtures.', 'Demo Tools Co', 129, 'SEED-TEMPLATE-STORE-01', '06012345678901', 50, 'https://images.pexels.com/photos/3877525/pexels-photo-3877525.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'fe86dce1-c9f6-4f53-a08e-bf7c11eaf888'::uuid, 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, 'hero, new_arrival', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, brand, price, sku, ean, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('df3af343-0b79-496a-b09f-6961731c35f8'::uuid, '__TENANT_UUID__'::uuid, 'Metric socket set', 'Chrome vanadium sockets 8–19mm with ratchet.', 'Demo Tools Co', 48, 'SEED-TEMPLATE-STORE-02', '06012345678918', 50, 'https://images.pexels.com/photos/4480531/pexels-photo-4480531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'fe86dce1-c9f6-4f53-a08e-bf7c11eaf888'::uuid, 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, brand, price, sku, ean, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('7a341f16-92e6-4028-b7be-a8bc99498433'::uuid, '__TENANT_UUID__'::uuid, 'Telescopic hedge trimmer', 'Reach tall hedges safely from the ground.', 'GardenPro', 89, 'SEED-TEMPLATE-STORE-03', '06012345678925', 50, 'https://images.pexels.com/photos/7813043/pexels-photo-7813043.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'c0e11c0d-65dc-4682-88a2-7eb464fe917b'::uuid, 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, 'seasonal', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, brand, price, sku, ean, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('3a08e5ab-49fc-4bb9-9e66-d732c32477cf'::uuid, '__TENANT_UUID__'::uuid, 'Compost bin 220L', 'Ventilated garden composter with lid.', 'GardenPro', 64, 'SEED-TEMPLATE-STORE-04', '06012345678932', 50, 'https://images.pexels.com/photos/5503338/pexels-photo-5503338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'c0e11c0d-65dc-4682-88a2-7eb464fe917b'::uuid, 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, brand, price, sku, ean, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('886d8791-3890-4498-8525-8aa36390e28e'::uuid, '__TENANT_UUID__'::uuid, 'Matt emulsion 10L — soft white', 'Washable wall paint for living rooms and bedrooms.', 'ColourHaus', 42, 'SEED-TEMPLATE-STORE-05', '06012345678949', 50, 'https://images.pexels.com/photos/7217981/pexels-photo-7217981.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '673df80c-a68f-44fe-a7e6-ee14432b92b6'::uuid, 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, brand, price, sku, ean, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('509e6597-048b-464d-956f-b56a7b66169e'::uuid, '__TENANT_UUID__'::uuid, 'Decorator’s roller set', '9" roller, tray, and extension pole.', 'ColourHaus', 24, 'SEED-TEMPLATE-STORE-06', '06012345678956', 50, 'https://images.pexels.com/photos/5691624/pexels-photo-5691624.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '673df80c-a68f-44fe-a7e6-ee14432b92b6'::uuid, 'f35ec173-f84e-45f8-89a8-8586a9007d59'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9b12c805-a7b5-43bb-86fb-28e5a70195e7'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-products', 0, 'home', 'home_main_feed', 'full', 'product_list', 'Project starters the trade desk promotes', 'Drills, garden lines, and paint — curated SKUs for weekend DIY missions.', NULL, NULL, NULL, NULL, 'c65ff313-d80d-4dba-bfae-516c472ffb18,df3af343-0b79-496a-b09f-6961731c35f8,7a341f16-92e6-4028-b7be-a8bc99498433,3a08e5ab-49fc-4bb9-9e66-d732c32477cf,886d8791-3890-4498-8525-8aa36390e28e,509e6597-048b-464d-956f-b56a7b66169e', NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9e60a906-1da1-43aa-8b3c-2a17b31b0d34'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-search', 1, 'home', 'home_main_feed', 'full', 'search_terms', 'Aisles shoppers combine', 'OR search pulls tools, consumables, and outdoor lines in one grid.', NULL, NULL, NULL, NULL, NULL, 'drill, roller, hedge, compost, emulsion, socket set', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('3cb6e54d-2331-47a2-b956-227d878000f0'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-blurb', 2, 'home', 'home_main_feed', 'full', 'blurb', 'Plan your project', NULL, 'Build your basket from departments or project kits. CMS blocks highlight seasonal paint and garden lines. For You suggests fasteners, PPE, and consumables.', NULL, '/catalogue', 'Browse departments', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('413c8d2e-b1a1-4921-90c7-914ea0622ac0'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-half-a', 3, 'home', 'home_main_feed', 'half', 'blurb', 'Power tools & fixings', NULL, 'Cordless kits and socket sets for shelves, curtain rails, and small builds — keep half-width for dense mobile layouts.', NULL, '/catalogue?category=template-store-tools', 'Tools', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6f274ec3-8eb3-404d-84a3-ec7dc829f550'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-half-b', 4, 'home', 'home_main_feed', 'half', 'blurb', 'Garden weekend', NULL, 'Trimming, composting, and outdoor storage — pair with paint for fence refresh weekends.', NULL, '/catalogue?category=template-store-garden', 'Garden', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6b352a3e-7b38-4bcc-b474-274ab6d229cd'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-main-image', 5, 'home', 'home_main_feed', 'full', 'image_blurb', 'Bank holiday project event', NULL, 'Deals ribbon for multi-buy paint, tool bundles, and outdoor prep.', 'https://images.pexels.com/photos/36378855/pexels-photo-36378855.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9ba64ebc-8bc7-48b1-9e00-11bcca2b0a5b'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-below-well', 1, 'home', 'home_below_context_well', 'full', 'blurb', 'Click & collect windows', NULL, 'Cut-off times, branch stock, and weather notes for outdoor work.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('672413e5-409f-434c-8feb-57435de92e05'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-between-missions', 1, 'home', 'home_between_missions_and_feed', 'full', 'blurb', 'How-to & projects', NULL, 'Short line linking workshops, measure services, or YouTube-style project IDs — two sentences max.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('5eda4ae1-dc8e-4bc0-8bb0-aa960506024d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-home-below-feed', 1, 'home', 'home_below_feed', 'full', 'blurb', 'Everything for the job', NULL, 'Project kits and multi-SKU bundles.', NULL, '/combos', 'Kits & bundles', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('aeaef8c8-fdf3-493a-89e5-ff6eedb0c0de'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-for-you-blocks', 1, 'for_you', 'for_you_below_cart_blocks', 'full', 'search_terms', 'Finish the job', 'Blades, sandpaper, brushes, and PPE before checkout.', NULL, NULL, NULL, NULL, NULL, 'roller, brush, sandpaper, gloves, tape, drill bit', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('a53ee242-70db-4932-a67a-50721b6cc13c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-for-you-header', 1, 'for_you', 'for_you_below_header', 'full', 'blurb', 'Based on your basket', NULL, 'Suggested add-ons and bundles. CMS can add static reminders (tape, bits, PPE).', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('8ecad4dd-6600-4ba9-b790-ada70328830d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-above', 1, 'catalogue', 'catalogue_above_grid', 'full', 'blurb', 'Departments in one grid', NULL, 'Filter tools, garden, and paint-decor. Search accepts project phrases (“fence stain Saturday”).', NULL, '/catalogue', 'Reset filters', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('9f939cb2-dcd7-4f6e-a548-ec27a7f84d57'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-below', 1, 'catalogue', 'catalogue_below_filters', 'full', 'search_terms', 'Trending searches', 'Broad OR across DIY staples.', NULL, NULL, NULL, NULL, NULL, 'drill, paint, roller, garden, compost, socket', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('1aa70a40-5ffa-4281-8a23-caec5a207bed'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cat-paint', 2, 'catalogue', 'catalogue_below_filters', 'full', 'blurb', 'Paint & decor aisle', NULL, 'You’re in Paint & decor — upsell rollers, trays, and masking tape. Link to tools for prep work.', NULL, '/catalogue?category=template-store-tools', 'Tools', NULL, NULL, NULL, NULL, NULL, 'template-store-paint-decor', now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('bafa32c3-50d5-42fc-8739-5ea4e10dff02'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-pdp-tabs', 1, 'product_detail', 'pdp_below_tabs', 'full', 'blurb', 'Specs & safety', NULL, 'Torque, voltage, VOC, and PPD warnings belong here — keep legal copy out of titles.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('5398c872-c011-4e1d-9072-f6a169f34fc9'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-pdp-context', 1, 'product_detail', 'pdp_below_context', 'full', 'blurb', 'Returns & guarantees', NULL, 'Link to your store policy for opened paint and tool warranties.', NULL, '/about', 'Our standards', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('bf79042a-b30c-4d1e-b5d2-31b80ac29db2'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-title', 1, 'recipe', 'recipe_below_title', 'full', 'blurb', 'Project night fuel', NULL, 'Tie recipe missions to quick meals when customers shop long DIY sessions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('3e06f3b6-d0ba-429c-ac33-ad8ea5b7cb7d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-ingredients', 1, 'recipe', 'recipe_below_ingredients', 'full', 'blurb', 'Missing a line item?', NULL, 'Search the catalogue or open For You for related add-ons.', NULL, '/for-you', 'Open For You', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('95ef04d1-ab6c-478a-b40c-7c10458dcfb1'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-recipe-index', 1, 'recipe_index', 'recipes_index_below_header', 'full', 'blurb', 'While paint dries', NULL, 'Quick indoor jobs between coats — fasteners, lighting, and small tools.', NULL, '/', 'Back to home', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('6feb6bae-542b-4611-970e-66bee5e4a782'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-checkout-summary', 1, 'checkout', 'checkout_above_summary', 'full', 'blurb', 'Almost done', NULL, 'Heavy or oversized lines may need separate delivery — confirm with ops copy.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('ecc6d16a-a207-4a52-9540-d12a6e220a83'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-checkout-sidebar', 1, 'checkout', 'checkout_sidebar', 'full', 'blurb', 'Need help?', NULL, 'Trade desk hours, hire services, and tool hotline — sidebar CMS slot.', NULL, '/about', 'Contact', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('decdb071-1dfd-4718-a63e-4cbd1946aaa0'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cart-above', 1, 'cart', 'cart_above_lines', 'full', 'blurb', 'Review quantities', NULL, 'Bundles sync with For You — drop duplicate heavy items before route planning.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('e3eed74a-1aff-4130-ac71-55fbec491feb'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-cart-below-bundle', 1, 'cart', 'cart_below_bundle', 'full', 'blurb', 'Complete the project', NULL, 'Cross-sell consumables: screws, anchors, filler.', NULL, '/catalogue?category=template-store-tools', 'Tools', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('1d8f0c8f-39c3-4831-8d07-4c101aae6692'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-offers', 1, 'offers', 'offers_below_header', 'full', 'blurb', 'Live savings', NULL, 'Multi-buy paint, garden bundles, and tool kits — keep the strip short.', NULL, '/catalogue', 'Shop all', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('270af101-7ec1-4278-84b7-c31054ddc3de'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-promotions', 1, 'promotions', 'promotions_below_header', 'full', 'blurb', 'Bank holiday & season', NULL, 'BBQ build, spring garden, winter heating prep — align with local campaigns.', NULL, '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('679c6ac5-f6f6-4021-bdaa-02fb8f09cfe3'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-store-about', 1, 'about', 'about_main', 'full', 'image_blurb', 'Example Store', NULL, 'Catalogue + Holmes + CMS blocks let merchandisers run DIY events without app releases.', 'https://images.pexels.com/photos/3926796/pexels-photo-3926796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/catalogue', 'Start shopping', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
COMMIT;
